env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 12
extends:
  - airbnb-base
  - prettier
  - plugin:jest/recommended
  - plugin:prettier/recommended
plugins:
  - prettier
  - jest
  - json
rules:
  prefer-arrow-callback: error
  no-console: error
