name: Build & Test & Deploy

on: push

jobs:
  check_deploy:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 10
          - 12
          - 14
        architecture:
          - x64
        # an extra windows-x86 run:
        include:
          - os: windows-2016
            node_version: 12
            architecture: x86
    steps:
      # Prepare
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      # Fetch dependencies
      - name: Fetch dependencies
        run: npm ci
      # Linters
      - name: Linting
        run: npm run lint
      # Testing
      - name: Testing
        run: npm run test
