name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cancel:
    runs-on: ubuntu-latest
    name: Cancel previous jobs
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - cancel
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node version
        uses: actions/setup-node@v2.1.4
      - name: Install Packages
        run: npm ci
      - name: Lint Files
        run: npm run lint
  test:
    name: Test
    timeout-minutes: 5
    needs:
      - lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - '15'
          - '14'
          - '12'
          - '10'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}
      - name: Node version
        run: node -v && npm -v
      - name: Fetch dependencies
        run: npm ci
        if: ${{ !startswith(matrix.node, '15') }}
      - name: Fetch dependencies
        run: npm ci --legacy-peer-deps
        if: ${{ startswith(matrix.node, '15') }}
      - name: Testing
        run: npm run test
