name: Build & Test & Deploy

on: push

jobs:
  check_deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v2.1.4
      # Fetch dependencies
      - name: Fetch dependencies
        run: npm ci
      # Linters
      - name: Linting
        run: npm run lint
      # Testing
      - name: Testing
        run: npm run test
